name: dart_toy
description: A sample web application
dependencies:
  browser: any
  polymer: ">=0.10.0 <0.11.0"
dev_dependencies:
  unittest: '>=0.11.0'
transformers:
  - polymer:
    entry_points: web/dijkstra/dijkstra.html