name: dart_examples
description: Web application showing example code in Dart language.
dependencies:
  browser: any
  polymer: ">=0.10.0 <0.11.0"
dev_dependencies:
  unittest: '>=0.11.0'
transformers:
- polymer:
    entry_points: web/dijkstra/dijkstra.html
